{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "xray-webhook-2-slack-example.serviceAccountName" . }}
  labels:
{{ include "xray-webhook-2-slack-example.labels" . | nindent 4 }}
{{- end -}}
